### ISSUE TITLE
Feature: User can create a group

### ISSUE THREAD

**Issue by saraysc** [saraysc/final-project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can create a new group

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can create a group name, group information, and picture of the group

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="410" alt="image" src="https://user-images.githubusercontent.com/113648549/210199140-18109bbe-94aa-43d1-8f6d-e404fc643a42.png">
<img width="89" alt="image" src="https://user-images.githubusercontent.com/113648549/210199200-4f38bef3-b749-4a6e-b0c8-c0f9eb6a4f9e.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Import tables from db designer into squema.sql
- [x] Update data.sql to insert data

### ☁️ Server Tasks

- [x] Have a 'post' request in `server/index.js` and insert the new group data into group table
- [x] Install all dependencies of package.json
- [x] Create a 'get' request to collect data from database
- [x]  create a url for the image by combining '/images' with req.file.filename
- [x]  insert the "caption" and "url" into the "group" table
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create component group.jsx
- [x] Create group class 
- [x] have the property caption, groupName, groupInfo inside the this.state and assign it to an empty string
- [x] create handleCaptionChange method inside the class that has an event as parameter
- [x] Bind handleCaptionChange inside the constructor.
- [x] Create a `new` FormData object.
- [x] Append  "caption" the value of this.state.caption and  "image" the value of this.fileInputRef.current.files[0] entries to the form data object.
- [x] Use fetch() to send a POST request to api

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
