### ISSUE TITLE
Feature: User can create a post

### ISSUE THREAD

**Issue by saraysc** [saraysc/final-project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a post

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
When clicking the '+' sign, User can create a post inside a group, that has the comment and post picture

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="413" alt="image" src="https://user-images.githubusercontent.com/113648549/210199474-bc8da52d-5114-4183-894a-8051293dc358.png">
<img width="409" alt="image" src="https://user-images.githubusercontent.com/113648549/210199397-058e5a8a-4c7b-4f35-b4d0-d35cdc5c9728.png">
<img width="91" alt="image" src="https://user-images.githubusercontent.com/113648549/210199469-a6672684-1dfa-42e6-8413-fa280c81fe8c.png">
<img width="92" alt="image" src="https://user-images.githubusercontent.com/113648549/210199413-4227a77d-79ab-4957-bc33-1e363324c5f8.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x]  Import tables from db designer into squema.sql
- [x]  Update data.sql to insert starting data

### ☁️ Server Tasks

- [x]  Have a 'post' request in server/index.js and insert the new post data into post table
 - [x]  Create a 'get' request to collect data from database
- [x]   create a url for the image 
- [x]   Handle all errors and respond to the client

### ⚡ Client Tasks

- [x]   Create component post.jsx
- [x]   Create post class
- [x]   have the property postInfo and postPicture inside the this.state and assign it to an empty string
- [x]   create handleChange method inside the class that has an event as parameter
- [x]   Bind handleChange inside the constructor.
- [x]  Create handleSubmit and bind it inside the constructor
- [x]  Have a fetch request to save the data object to the database
- [x] Create new form data Object
- [x] Render the image

### 🧑‍⚕️ Clean Up Tasks

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
