### ISSUE TITLE
Feature: User can comment in a post

### ISSUE THREAD

**Issue by saraysc** [saraysc/final-project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can comment in a post

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can comment under a post 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/113648549/210201697-9b7604ae-ce20-4d49-af33-e141621ce147.png">
<img width="88" alt="image" src="https://user-images.githubusercontent.com/113648549/210201717-3c9a1710-9265-4003-8cf1-1c24ac1a5d4c.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Import tables from db designer into squema.sql
- [ ] Update data.sql to insert starting data

### ☁️ Server Tasks

- [ ]  Have a 'post' request in server/index.js and insert the new group data into comments table
- [ ]   Create a 'get' request to collect data from the database
 - [ ]  Handle all errors and respond to the client

### ⚡ Client Tasks

 - [ ]  Create component comments.jsx
 - [ ] Create comment class
 - [ ]  have the property comment inside the this.state and assign it to an empty string
 - [ ]  create addComment method inside the class 
 - [ ]  Bind addComment inside the constructor.
 - [ ]  Have a fetch request to save the data object to the database

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
