### ISSUE TITLE
Feature: User can create an account

### ISSUE THREAD

**Issue by saraysc** [saraysc/final-project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User can create an account that has name, username, password, email, and profile picture.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="410" alt="image" src="https://user-images.githubusercontent.com/113648549/210186875-9ae97eec-db50-46f2-91c8-c2c66de46511.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Import tables from db designer into squema.sql
- [ ] Add the new account into the users table of data.sql

### ☁️ Server Tasks

- [ ] Have a 'post' request in `server/index.js` and insert the new account data into users table
- [ ] Create a 'get' request to collect data from database
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create component account.jsx
- [ ] Create account class 
- [ ] create handleChange method inside the account that will save the inputs
value into this.state
- [ ] Bind handleChange into the constructor.
- [ ] Create username and password properties inside this.state and assign the value of an empty string
- [ ] Create handleSubmit method and have event.preventDefault()
- [ ] Bind handleSubmit method into the constructor
- [ ] Use fetch() to send a POST request to api

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
