### ISSUE TITLE
Feature: User can like/dislike a comment

### ISSUE THREAD

**Issue by saraysc** [saraysc/final-project#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can like/dislike a comment

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the user comments under a post, user can like/dislike a comment

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="407" alt="image" src="https://user-images.githubusercontent.com/113648549/210202822-66f3c774-5ac3-435e-87f8-f824fe360d74.png">
<img width="90" alt="image" src="https://user-images.githubusercontent.com/113648549/210202796-5a78cd56-416d-45d6-a82e-b1c9f0ba7820.png">
## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ]  Import tables from db designer into squema.sql
- [ ] Update data.sql to insert starting data

### ☁️ Server Tasks

 - [ ]  Have a 'post' request in server/index.js and insert the new group data into comments table
 - [ ]  Create a 'get' request to collect data from the database
 - [ ]  Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ]  Create component commentsLike.jsx
- [ ] Create commentsLike class
- [ ]have the property like and assign inside the this.state and assign it to false
- [ ] create like and dislike method inside the class and assign it to true when one of them is clicked
- [ ] Bind like/dislike method inside the constructor.
- [ ] Have a fetch request to save the data object to the database

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
