### ISSUE TITLE
Feature: User can log in

### ISSUE THREAD

**Issue by saraysc** [saraysc/final-project#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can log in

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After the account is created, user can type their username and password to log in into their account
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="409" alt="image" src="https://user-images.githubusercontent.com/113648549/210203196-98558fee-c757-4e8b-ae44-208239a2a5d1.png">
<img width="88" alt="image" src="https://user-images.githubusercontent.com/113648549/210203231-f52733cf-795b-4b9f-90b1-11557664b8c3.png">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [ ]Query the users database to find the "userId" and "password".
- [ ] Create a payload object containing the user's "userId" and "username".
- [ ] Create a new signed token with `jwt.sign()`, using the payload and your TOKEN_SECRET
- [ ] Send the client a 200 response containing the payload and the token.

### ⚡ Client Tasks

- [ ] create app.jsx
- [ ] create app class
- [ ] create handleSignIn inside the class and bind it inside the constructor
- [ ] if sign-in is completed, handleSignIn() is called and saves the token into the window.localStorage
- [ ] user is updated in the state and the AuthForm is re-rendered

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
